changelog:
  exclude:
    labels:
      - ignore-for-release-notes
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Features and enhancements
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
    - title: Documentation updates
      labels:
        - documentation
    - title: Bump dependencies
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"